# This sets the environment for building Kiwix JS store packages and runs the build script

name: Build all packages on release publish

# Controls when the action will run.
on:
  # Triggers the workflow on release publish
  release:
    types: [ published ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Decrypt the ssh secret
      - name: Decrypt files and set constants
        env:
          SSH_KEY: ${{ secrets.SSH_KEY }}
          MOZILLA_API_SECRET: ${{ secrets.MOZILLA_API_SECRET }}
          MOZILLA_API_KEY: ${{ secrets.MOZILLA_API_KEY }}
          TAG_NAME: ${{ github.event.release.tag_name }}
        shell: bash
        run: |
          echo "$SSH_KEY" > ./scripts/ssh_key
          chmod 600 ./scripts/ssh_key
          ls -al ./scripts/

      # Set up the environment
      - name: Setup environment
        shell: bash
        run: |
          sudo apt-get update
          sudo apt-get --yes install ./ubuntu_touch/*.deb

      # Runs the build scripts
      - name: Run the build scripts
        shell: bash
        # Switch -t indicates a tag release; -d indicates dry run (for testing)
        # TESTING ONLY: setting TAG_NAME to 0.0.0 for testing becuase github.event.release.tag_name
        # only exists if the release event has fired (remove this before merging to master)
        run: |
          if [ "x$TAG_NAME" = "x" ]; then
            TAG_NAME="0.0.0"
          fi
          echo "TAG_NAME is set to $TAG_NAME"
          DISPLAY=:99.0 ./scripts/create_all_packages.sh -t -d -v "$TAG_NAME"
