# This is a basic workflow to help you get started with Actions

name: Build all packages on release publish

# Controls when the action will run.
on:
  # Triggers the workflow on release publish
  release:
    types: [ published ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Decrypt the ssh secret
      - name: Decrypt files
        env:
          SSH_KEY: ${{ secrets.SSH_KEY }}
          MOZILLA_API_SECRET: ${{ secrets.MOZILLA_API_SECRET }}
          MOZILLA_API_KEY: ${{ secrets.MOZILLA_API_KEY }}
          GHWS: ${{ github.workspace }}
          TAG_NAME: ${{ github.event.release.tag_name }}
        run: |
          echo "$SSH_KEY" | base64 -d > ssh_key
          chmod 600 ssh_key

      # Set up the environment
      - name: Setup environment
        run: sudo apt-get --yes install ./$GHWS/ubuntu_touch/*.deb

      # Runs a command using the runner's shell
      - name: Run a script
      # Switch -t sets the version number from the current tag; -d indicates dry run (for testing)
        run: sh DISPLAY=:99.0 ./$GHWS/scripts/create_all_packages.sh -t -v $TAG_NAME -d
