# Workflow to update docker image for moz-extension.kiwix.org (since docker autobuild has been disabled)
# This workflow uses openzim/docker-publish-action@v6
# Documentation: https://github.com/openzim/docker-publish-action#readme

name: Publish Docker container for Mozilla extension

# Controls when the action will run.
on:
  # Triggers the workflow when a release is published or updated
  release:
    types: [ published ]

  # DEV: You can call this dispatch for testing from the REST API and set input values with
  # "inputs": {
  #    "version": "{tag}"
  # }
  # API: 'https://api.github.com/repos/{owner}/{repo}/actions/workflows/{workflow_id}/dispatches'
  # Documentation of API: https://docs.github.com/en/rest/reference/actions#create-a-workflow-dispatch-event
  workflow_dispatch:
    inputs:
      version:
        description: Specific version to build (overrides on-master and tag-pattern)
        required: false
        default: ''

jobs:
  build-and-push:
    name: Deploy Docker Image
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Modify version in source files
        env:
          INPUT_VERSION = ${{ github.event.inputs.version }}
          TAG_VERSION = ${{ github.event.release.tag_name }}
        run: |
          # Use the override value by preference
          VERSION=${INPUT_VERSION}
          # If no override input was entered, use the release tag
          if [ ! $VERSION ]; then
            VERSION=${TAG_VERSION}
          fi
          if [ $VERSION ]; then
            # Set the required version in files to be copied to docker container
            sed -i -E "s/appVersion\s*=\s*[^;]+/appVersion = '$VERSION'/" ./service-worker.js
            sed -i -E "s/params..appVersion[^=]+?=\s*[^;]+/params['appVersion'] = '$VERSION'/" ./www/js/app.js
          fi
      - name: Build and push
        uses: openzim/docker-publish-action@v6
        with:
          image-name: kiwix/kiwix-moz-extension
          credentials: |
            DOCKERIO_USERNAME=${{ secrets.DOCKERHUB_USERNAME }}
            DOCKERIO_TOKEN=${{ secrets.DOCKERHUB_PASSWORD }}
          tag-pattern: /^[0-9]([0-9.]+).*$/
          latest-on-tag: true
          dockerfile: docker/dockerfile-moz-extension.pwa
          restrict-to: kiwix/kiwix-js
          registries: docker.io
          manual-tag: ${{ github.event.inputs.version }}
